project:
  type: website

website:
  title: "Introduction to Bioinformatics NGS"
  navbar:
    left:
      - href: server_accounts.qmd
        text: Server Accounts
      - href: server_access.qmd
        text: Server Access      
      - href: index.qmd
        text: Data
      - href: NGS1.qmd
        text: Quality Control
      - href: NGS2.qmd
        text: Mapping


format: 
  html:
    code-fold: true
    code-summary: "Click here to show the code"
    code-tools: true
    theme: flatly
    self-contained: true
    page-layout: full
    toc: true
    toc-depth: 4
    css: styles.css
# engine: knitr

execute:
  freeze: auto


